import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Library App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='bg-indigo-900 text-indigo-200 min-h-screen flex items-center justify-center antialiased tracking-tight'>{children}</div>
      </body>
    </html>
  );
}
